package br.ifmg.edu.trabalho_java_avancado.visao;

import br.ifmg.edu.trabalho_java_avancado.modelo.Adm;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroAdm.CadastroAdmListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroMateria.CadastroMateriaListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroProdTerceiros.CadastroProdTercListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroVendedores.CadastroVendedorListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroFornecedor.CadastroFornecedorListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.CadastroProdProduzidos.CadastroProdProduzidosListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.Producao.CadastroProducaoListagem;
import br.ifmg.edu.trabalho_java_avancado.visao.Relatórios.RelatorioFornecedores;
import br.ifmg.edu.trabalho_java_avancado.visao.Relatórios.RelatorioFuncionarios;
import br.ifmg.edu.trabalho_java_avancado.visao.Relatórios.RelatorioMateriaPrima;
import br.ifmg.edu.trabalho_java_avancado.visao.Relatórios.RelatorioProdProduzidos;
import br.ifmg.edu.trabalho_java_avancado.visao.Relatórios.RelatorioProdTerceirizados;
import br.ifmg.edu.trabalho_java_avancado.visao.Relatórios.RelatorioProducao;
import br.ifmg.edu.trabalho_java_avancado.visao.Relatórios.RelatorioVenda;
import br.ifmg.edu.trabalho_java_avancado.visao.Vendas.CadastroVendasListagem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.Timer;

/**
 *
 * @author Vitor
 */
public class VisaoPrincipal_Adm extends javax.swing.JFrame {

    /**
     * Creates new form VisaoPrincipal
     */
    
    private Adm a;
    
    public VisaoPrincipal_Adm(Adm vendedor) {
        initComponents();
        this.a = vendedor;
        Timer timer = new Timer(1000,ativar);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblHora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuAdm = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jSubMenuAdm = new javax.swing.JMenuItem();
        jSubMenuFornecedor = new javax.swing.JMenuItem();
        jSubMenuMateria = new javax.swing.JMenuItem();
        jSubMenuProdProduzido = new javax.swing.JMenuItem();
        jSubMenuProdTerc = new javax.swing.JMenuItem();
        jSubMenuVendedor = new javax.swing.JMenuItem();
        jMenuProducao = new javax.swing.JMenu();
        jSubMenuIniciaProducao = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jSubMenuVenda = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuListagens = new javax.swing.JMenu();
        jMIAdm = new javax.swing.JMenuItem();
        jMIFornecedores = new javax.swing.JMenuItem();
        jMIMP = new javax.swing.JMenuItem();
        jMIProdProduzidos = new javax.swing.JMenuItem();
        jMIProdTerceirizados = new javax.swing.JMenuItem();
        jMIVenda = new javax.swing.JMenuItem();
        jMIProducao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Padaria");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pao.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jlblHora.setText("xxxxxxx, dd/mm/yyyy 00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblHora)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlblHora)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel3.setText("Panificadora Chega Manteiga,Derrete!");
        jLabel3.setToolTipText("");

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuCadastro.setText("Cadastros");

        jSubMenuAdm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuAdm.setText("Adminstradores");
        jSubMenuAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuAdmActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuAdm);

        jSubMenuFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuFornecedor.setText("Fornecedor");
        jSubMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuFornecedor);

        jSubMenuMateria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuMateria.setText("Matérias-Primas");
        jSubMenuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuMateriaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuMateria);

        jSubMenuProdProduzido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuProdProduzido.setText("Produtos Produzidos");
        jSubMenuProdProduzido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuProdProduzidoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuProdProduzido);

        jSubMenuProdTerc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuProdTerc.setText("Produtos Terceirizados");
        jSubMenuProdTerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuProdTercActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuProdTerc);

        jSubMenuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuVendedor.setText("Vendedores");
        jSubMenuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuVendedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSubMenuVendedor);

        jMenuAdm.add(jMenuCadastro);

        jMenuProducao.setText("Produção");

        jSubMenuIniciaProducao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuIniciaProducao.setText("Produções");
        jSubMenuIniciaProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuIniciaProducaoActionPerformed(evt);
            }
        });
        jMenuProducao.add(jSubMenuIniciaProducao);

        jMenuAdm.add(jMenuProducao);

        jMenuVendas.setText("Vendas");

        jSubMenuVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jSubMenuVenda.setText("Vendas");
        jSubMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuVendaActionPerformed(evt);
            }
        });
        jMenuVendas.add(jSubMenuVenda);

        jMenuAdm.add(jMenuVendas);

        jMenuRelatorios.setText("Relatórios");

        jMenuListagens.setText("Listagens");

        jMIAdm.setText("Administradores/Vendedores");
        jMIAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAdmActionPerformed(evt);
            }
        });
        jMenuListagens.add(jMIAdm);

        jMIFornecedores.setText("Fornecedores");
        jMIFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFornecedoresActionPerformed(evt);
            }
        });
        jMenuListagens.add(jMIFornecedores);

        jMIMP.setText("Matérias-Primas");
        jMIMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMPActionPerformed(evt);
            }
        });
        jMenuListagens.add(jMIMP);

        jMIProdProduzidos.setText("Produtos Produzidos");
        jMIProdProduzidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdProduzidosActionPerformed(evt);
            }
        });
        jMenuListagens.add(jMIProdProduzidos);

        jMIProdTerceirizados.setText("Produtos Terceirizados");
        jMIProdTerceirizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProdTerceirizadosActionPerformed(evt);
            }
        });
        jMenuListagens.add(jMIProdTerceirizados);

        jMenuRelatorios.add(jMenuListagens);

        jMIVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIVenda.setText("Vendas");
        jMIVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVendaActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMIVenda);

        jMIProducao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIProducao.setText("Produções");
        jMIProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProducaoActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMIProducao);

        jMenuAdm.add(jMenuRelatorios);

        setJMenuBar(jMenuAdm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(756, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSubMenuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuVendedorActionPerformed
        CadastroVendedorListagem dialog = new CadastroVendedorListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuVendedorActionPerformed

    private void jSubMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuFornecedorActionPerformed
        CadastroFornecedorListagem dialog = new CadastroFornecedorListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuFornecedorActionPerformed

    private void jSubMenuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuMateriaActionPerformed
        CadastroMateriaListagem dialog = new CadastroMateriaListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuMateriaActionPerformed

    private void jSubMenuProdTercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuProdTercActionPerformed
        CadastroProdTercListagem dialog = new CadastroProdTercListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuProdTercActionPerformed

    private void jSubMenuAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuAdmActionPerformed
        CadastroAdmListagem dialog = new CadastroAdmListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuAdmActionPerformed

    private void jSubMenuProdProduzidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuProdProduzidoActionPerformed
        CadastroProdProduzidosListagem dialog = new CadastroProdProduzidosListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuProdProduzidoActionPerformed

    private void jSubMenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuVendaActionPerformed
        CadastroVendasListagem dialog = new CadastroVendasListagem(this, true, a);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuVendaActionPerformed

    private void jSubMenuIniciaProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuIniciaProducaoActionPerformed
        CadastroProducaoListagem dialog = new CadastroProducaoListagem(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jSubMenuIniciaProducaoActionPerformed

    private void jMIVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVendaActionPerformed
        RelatorioVenda dialog = new RelatorioVenda(this, false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMIVendaActionPerformed

    private void jMIAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAdmActionPerformed
        RelatorioFuncionarios dialog = new RelatorioFuncionarios(this, false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMIAdmActionPerformed

    private void jMIProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProducaoActionPerformed
        RelatorioProducao dialog = new RelatorioProducao(this, false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMIProducaoActionPerformed

    private void jMIFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFornecedoresActionPerformed
        RelatorioFornecedores dialog = new RelatorioFornecedores(this, false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMIFornecedoresActionPerformed

    private void jMIMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMPActionPerformed
        RelatorioMateriaPrima dialog = new RelatorioMateriaPrima(this, false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMIMPActionPerformed

    private void jMIProdProduzidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdProduzidosActionPerformed
        RelatorioProdProduzidos dialog = new RelatorioProdProduzidos(this, false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMIProdProduzidosActionPerformed

    private void jMIProdTerceirizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProdTerceirizadosActionPerformed
        RelatorioProdTerceirizados dialog = new RelatorioProdTerceirizados(this, false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMIProdTerceirizadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMIAdm;
    private javax.swing.JMenuItem jMIFornecedores;
    private javax.swing.JMenuItem jMIMP;
    private javax.swing.JMenuItem jMIProdProduzidos;
    private javax.swing.JMenuItem jMIProdTerceirizados;
    private javax.swing.JMenuItem jMIProducao;
    private javax.swing.JMenuItem jMIVenda;
    private javax.swing.JMenuBar jMenuAdm;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuListagens;
    private javax.swing.JMenu jMenuProducao;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jSubMenuAdm;
    private javax.swing.JMenuItem jSubMenuFornecedor;
    private javax.swing.JMenuItem jSubMenuIniciaProducao;
    private javax.swing.JMenuItem jSubMenuMateria;
    private javax.swing.JMenuItem jSubMenuProdProduzido;
    private javax.swing.JMenuItem jSubMenuProdTerc;
    private javax.swing.JMenuItem jSubMenuVenda;
    private javax.swing.JMenuItem jSubMenuVendedor;
    private javax.swing.JLabel jlblHora;
    // End of variables declaration//GEN-END:variables
    
    ActionListener ativar = (
            new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Horas();
                }
            }            
        );
    
    
    private void Horas() {
            
        Calendar hora = Calendar.getInstance(getLocale());
        int hh = hora.get(Calendar.HOUR_OF_DAY);
        int mm = hora.get(Calendar.MINUTE);
        int ss = hora.get(Calendar.SECOND);

        int dia = hora.get(Calendar.DAY_OF_MONTH);
        int mes = hora.get(Calendar.MONTH);
        int ano = hora.get(Calendar.YEAR);

        int sem = hora.get(Calendar.DAY_OF_WEEK);
        String semana = "";
        switch (sem){
            case 7: semana = "Sábado";break;
            case 1: semana = "Domingo";break;
            case 2: semana = "Segunda-feira";break;
            case 3: semana = "Terça-feira";break;
            case 4: semana = "Quarta-feira";break;
            case 5: semana = "Quinta-feira";break;
            case 6: semana = "Sexta-feira";break;
        }

        jlblHora.setText(
          semana+", "+formatar(dia)+"/"+
                      formatar(++mes)+"/"+
                      formatar(ano)+" - Horas: "+
                      formatar(hh)+":"+
                      formatar(mm)+":"+
                      formatar(ss)
        );

    }
    
    private String formatar(int num){
        DecimalFormat df = new DecimalFormat("00");
        return df.format(num);
    }
}
