package br.ifmg.edu.trabalho_java_avancado.visao.Relatorios;

import br.ifmg.edu.trabalho_java_avancado.util.RelatorioUtils;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class RelatorioVenda extends javax.swing.JDialog {

    private RelatorioUtils util;

    /**
     * Creates new form RelatorioVenda
     *
     * @param parent Janela Pai
     * @param modal Para definir se é modal ou não
     */
    public RelatorioVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        util = new RelatorioUtils();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodVendedor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFmtDataInício = new javax.swing.JFormattedTextField();
        jFmtDataFim = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioPDF = new javax.swing.JRadioButton();
        jRadioVis = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jBtnGera = new javax.swing.JButton();
        jBtnFecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Padaria");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jLabel1.setText("Código do Vendedor:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro por Data:"));

        jLabel2.setText("Data de Início:");

        jLabel3.setText("Data de Fim:");

        jFmtDataInício.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jFmtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFmtDataInício, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFmtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtDataInício, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFmtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Visuzalização");

        buttonGroup1.add(jRadioPDF);
        jRadioPDF.setText("Gerar PDF");

        buttonGroup1.add(jRadioVis);
        jRadioVis.setText("Visualizar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioVis, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jRadioPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioVis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCodVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnGera.setText("Gerar Relatório");
        jBtnGera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGeraActionPerformed(evt);
            }
        });

        jBtnFecha.setText("Fechar");
        jBtnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jBtnGera)
                .addGap(18, 18, 18)
                .addComponent(jBtnFecha)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGera)
                    .addComponent(jBtnFecha))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(363, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFechaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnFechaActionPerformed

    private void jBtnGeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGeraActionPerformed

        Date data1 = null;
        Date data2 = null;
        if ((jTxtCodVendedor.getText().equals("") || jTxtCodVendedor.getText().trim().equals(""))
                && (jFmtDataFim.getText().equals("") || jFmtDataFim.getText().trim().equals(""))
                && (jFmtDataInício.getText().equals("") || jFmtDataInício.getText().trim().equals(""))) {
            if (jRadioVis.isSelected()) {
                util.VisualizaRelatorio("Relatório_Venda_Geral.jasper");
            } else if (jRadioPDF.isSelected()) {
                util.GeraRelatorio("Relatório_Venda_Geral.jasper", "Relatório_Venda_Geral.pdf");
            } else {
                JOptionPane.showMessageDialog(this, "Escolha um modo de Visualização", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else if (!(jTxtCodVendedor.getText().equals("") || jTxtCodVendedor.getText().trim().equals(""))
                && (jFmtDataFim.getText().equals("") || jFmtDataFim.getText().trim().equals(""))
                && (jFmtDataInício.getText().equals("") || jFmtDataInício.getText().trim().equals(""))) {

            Integer codigo;
            try {
                codigo = Integer.parseInt(jTxtCodVendedor.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Digite um Código válido!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String path = RelatorioVenda.class.getResource("Venda_Codigo_Detalhe.jasper").getPath();
            //System.out.println("Teste: "+path);
            HashMap<String, Object> parametros = new LinkedHashMap<>();
            parametros.put("codigoVendedor", codigo);
            parametros.put("PathRelAutores",path);

            if (jRadioVis.isSelected()) {
                util.VisualizaRelatorioParametro("Relatório_Venda_Código.jasper", parametros);
            } else if (jRadioPDF.isSelected()) {
                util.GeraRelatorioParametro("Relatório_Venda_Código.jasper", "Relatório_Venda_Código.pdf", parametros);
            } else {
                JOptionPane.showMessageDialog(this, "Escolha um modo de Visualização", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else if ((jTxtCodVendedor.getText().equals("") || jTxtCodVendedor.getText().trim().equals(""))
                && !(jFmtDataFim.getText().equals("") || jFmtDataFim.getText().trim().equals(""))
                && !(jFmtDataInício.getText().equals("") || jFmtDataInício.getText().trim().equals(""))) {

            HashMap<String, Object> parametros = new LinkedHashMap<>();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                data1 = new java.sql.Date(sdf.parse(jFmtDataInício.getText()).getTime());
                data2 = new java.sql.Date(sdf.parse(jFmtDataFim.getText()).getTime());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Verifique as Datas", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (data1.before(data2)) {
                parametros.put("DataInicio", data1);
                parametros.put("DataFim", data2);

            } else if (data1.after(data2)) {
                parametros.put("DataInicio", data2);
                parametros.put("DataFim", data1);
                JOptionPane.showMessageDialog(this, "As datas estão invertidas", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "As datas são iguais", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

            if (jRadioVis.isSelected()) {
                util.VisualizaRelatorioParametro("Relatório_Venda_Data.jasper", parametros);
            } else if (jRadioPDF.isSelected()) {
                util.GeraRelatorioParametro("Relatório_Venda_Data.jasper", "Relatório_Venda_Data.pdf", parametros);
            } else {
                JOptionPane.showMessageDialog(this, "Escolha um modo de Visualização", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            HashMap<String, Object> parametros = new LinkedHashMap<>();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                data1 = new java.sql.Date(sdf.parse(jFmtDataInício.getText()).getTime());
                data2 = new java.sql.Date(sdf.parse(jFmtDataFim.getText()).getTime());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Verifique as Datas", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Integer codigo;
            try {
                codigo = Integer.parseInt(jTxtCodVendedor.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Digite um Código válido!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            parametros.put("codigoVendedor", codigo);
            
            if (data1.before(data2)) {
                parametros.put("DataInicio", data1);
                parametros.put("DataFim", data2);

            } else if (data1.after(data2)) {
                parametros.put("DataInicio", data2);
                parametros.put("DataFim", data1);
                JOptionPane.showMessageDialog(this, "As datas estão invertidas", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "As datas são iguais", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

            if (jRadioVis.isSelected()) {
                util.VisualizaRelatorioParametro("Relatório_Venda_Código_Data.jasper", parametros);
            } else if (jRadioPDF.isSelected()) {
                util.GeraRelatorioParametro("Relatório_Venda_Código_Data.jasper", "Relatório_Venda_Código_Data.pdf", parametros);
            } else {
                JOptionPane.showMessageDialog(this, "Escolha um modo de Visualização", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnGeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            RelatorioVenda dialog = new RelatorioVenda(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnFecha;
    private javax.swing.JButton jBtnGera;
    private javax.swing.JFormattedTextField jFmtDataFim;
    private javax.swing.JFormattedTextField jFmtDataInício;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioPDF;
    private javax.swing.JRadioButton jRadioVis;
    private javax.swing.JTextField jTxtCodVendedor;
    // End of variables declaration//GEN-END:variables
}
